export default [
  {
    adult: false,
    backdrop_path: "/jlGmlFOcfo8n5tURmhC7YVd4Iyy.jpg",
    genre_ids: [28, 12, 14, 35],
    id: 436969,
    original_language: "en",
    original_title: "The Suicide Squad",
    overview:
      "Un grupo de super villanos se encuentran encerrados en Belle Reve, una prisión de alta seguridad con la tasa de mortalidad más alta de Estados Unidos. Para salir de allí harán cualquier cosa, incluso unirse al grupo Task Force X, dedicado a llevar a cabo misiones suicidas bajo las órdenes de Amanda Waller. Fuertemente armados son enviados a la isla Corto Maltese, una jungla repleta de enemigos.",
    popularity: 4013.503,
    poster_path: "/fPJWlhXA2VXf4MlQ3JenVsz1iba.jpg",
    release_date: "2021-07-28",
    title: "El Escuadrón Suicida",
    video: false,
    vote_average: 8,
    vote_count: 2969,
  },
  {
    adult: false,
    backdrop_path: "/swcF9sPlruc6s4gAHuWfbYicbqG.jpg",
    genre_ids: [16, 10751, 12, 35],
    id: 675445,
    original_language: "en",
    original_title: "PAW Patrol: The Movie",
    overview:
      "La Patrulla Canina está en racha. Cuando Humdinger, su mayor rival, se convierte en alcalde de la cercana Ciudad Aventura y empieza a causar estragos, Ryder y los heroicos cachorros se ponen en marcha para enfrentarse a este nuevo desafío. Mientras uno de los cachorros debe enfrentarse a su pasado en Ciudad Aventura, el equipo encuentra ayuda en una nueva aliada, la inteligente perrita salchicha Liberty. Juntos y armados con nuevos y emocionantes artefactos y equipos, la Patrulla Canina lucha por salvar a los ciudadanos de Ciudad Aventura.",
    popularity: 3574.462,
    poster_path: "/2Y5OZsWBksmEl2Dggfx46DfRkFO.jpg",
    release_date: "2021-08-09",
    title: "La patrulla canina: La película",
    video: false,
    vote_average: 7.8,
    vote_count: 164,
  },
  {
    adult: false,
    backdrop_path: "/7WJjFviFBffEJvkAms4uWwbcVUk.jpg",
    genre_ids: [12, 14, 35, 28],
    id: 451048,
    original_language: "en",
    original_title: "Jungle Cruise",
    overview:
      "Principios del siglo XX. Frank (Dwayne Johnson) es el carismático capitán de una peculiar embarcación que recorre la selva amazónica. Allí, a pesar de los peligros que el río Amazonas les tiene preparados, Frank llevará en su barco a la científica Lily Houghton (Emily Blunt) y a su hermano McGregor Houghton (Jack Whitehall). Su misión será encontrar un árbol místico que podría tener poderes curativos. Claro que su objetivo no será fácil, y en su aventura se encontrarán con toda clase de dificultades, además de una expedición alemana que busca también este árbol con propiedades curativas. Esta comedia de acción y aventuras está basada en la atracción Jungle Cruise de los parques de ocio de Disney.",
    popularity: 3406.403,
    poster_path: "/esgrxpxrQufea2A3iHJUquG4mdz.jpg",
    release_date: "2021-07-28",
    title: "Jungle Cruise",
    video: false,
    vote_average: 7.9,
    vote_count: 2063,
  },
  {
    adult: false,
    backdrop_path: "/uHmvk8FnoxpgujDU0RIXLkv2fNt.jpg",
    genre_ids: [16, 35],
    id: 573164,
    original_language: "es",
    original_title: "Un rescate de huevitos",
    overview: "Toto y Di son los padres de dos hermosos huevos: Uly y Max.",
    popularity: 2402.906,
    poster_path: "/lq68Z5htr1bjPd8X0U3PBZRcUij.jpg",
    release_date: "2021-08-12",
    title: "Un rescate de huevitos",
    video: false,
    vote_average: 8.1,
    vote_count: 140,
  },
  {
    adult: false,
    backdrop_path: "/AjQgFtfXTmmMVuaH2VfQDdGbeQH.jpg",
    genre_ids: [28, 18, 80],
    id: 706972,
    original_language: "en",
    original_title: "Narco Sub",
    overview:
      "Un hombre se convertirá en un criminal para salvar a su familia. Director: Shawn Welling Guionista: Derek H. Potts Estrellas: Tom Vera, Tom Sizemore, Lee Majors |",
    popularity: 2281.463,
    poster_path: "/7p0O4mKYLIhU2E5Zcq9Z3vOZ4e9.jpg",
    release_date: "2021-07-22",
    title: "Operación Narco",
    video: false,
    vote_average: 3.2,
    vote_count: 10,
  },
  {
    adult: false,
    backdrop_path: "/dq18nCTTLpy9PmtzZI6Y2yAgdw5.jpg",
    genre_ids: [28, 12, 53, 878],
    id: 497698,
    original_language: "en",
    original_title: "Black Widow",
    overview:
      "Natasha Romanoff, alias Viuda Negra, se enfrenta a las partes más oscuras de su historia cuando surge una peligrosa conspiración con vínculos con su pasado. Perseguida por una fuerza que no se detendrá ante nada para acabar con ella, Natasha debe enfrentarse a su historia como espía y a las relaciones rotas que dejó a su paso mucho antes de convertirse en una Vengadora.",
    popularity: 1917.443,
    poster_path: "/oggEsESyLjVGD7jbIdBfa2hFUrx.jpg",
    release_date: "2021-07-07",
    title: "Viuda negra",
    video: false,
    vote_average: 7.8,
    vote_count: 4481,
  },
  {
    adult: false,
    backdrop_path: "/8s4h9friP6Ci3adRGahHARVd76E.jpg",
    genre_ids: [16, 35, 10751, 878],
    id: 379686,
    original_language: "en",
    original_title: "Space Jam: A New Legacy",
    overview:
      "Secuela de la cinta original de 1996, Space Jam, protagonizada por Michael Jordan. En esta segunda parte, la super estrella de la NBA es LeBron James, quien queda atrapado junto a su hijo Dom en un extraño lugar, un espacio digital de una fuerza todopoderosa y malvada conocida como A.I. Para volver a casa y poner a salvo a su hijo, el jugador de baloncesto deberá unir fuerzas con Bugs Bunny, Lola Bunny y el resto de personajes de los Looney Tunes para enfrentarse en un partido de baloncesto a los campeones digitalizados por A.I.",
    popularity: 1876.991,
    poster_path: "/i6E8fx8lAEI0PGGCUlaA2Ap1gWi.jpg",
    release_date: "2021-07-08",
    title: "Space Jam: Nuevas leyendas",
    video: false,
    vote_average: 7.5,
    vote_count: 1923,
  },
  {
    adult: false,
    backdrop_path: "/lzLzKXq2C0kL5Pu7VW5sNl5KV6L.jpg",
    genre_ids: [12, 53, 18, 28],
    id: 597433,
    original_language: "en",
    original_title: "Beckett",
    overview:
      "Beckett (John David Washington), un estadounidense de vacaciones en Grecia, se convierte en víctima de una persecución tras un brutal accidente. Mientras emprende una huida desesperada por Grecia para salvar el pellejo, llegar a la embajada de Estados Unidos y lavar su nombre, la tensión va en aumento a medida que las autoridades estrechan el cerco, el malestar político aumenta, y Beckett se va adentrando más y más en una peligrosa e intrincada conspiración.",
    popularity: 1715.514,
    poster_path: "/fBJducGBcmrcIOQdhm4BUBNDiMu.jpg",
    release_date: "2021-08-04",
    title: "Beckett",
    video: false,
    vote_average: 6.2,
    vote_count: 204,
  },
  {
    adult: false,
    backdrop_path: "/j28p5VwI5ieZnNwfeuZ5Ve3mPsn.jpg",
    genre_ids: [35, 28, 12, 878],
    id: 550988,
    original_language: "en",
    original_title: "Free Guy",
    overview:
      "Un hombre descubre que en realidad es un personaje dentro de un videojuego. Guy (Ryan Reynolds) trabaja como cajero de un banco, es un tipo alegre y solitario al que nada la amarga el día. Incluso si le utilizan como rehén durante un atraco a su banco, él sigue sonriendo como si nada. Pero un día se da cuenta de que Free City no es exactamente la ciudad que él creía. Guy va a descubrir que en realidad es un personaje no jugable dentro de un brutal videojuego. Ahora que sabe que es un personaje de videojuego, Guy, acompañado por Molotov Girl (Jodie Comer), decidirá enfrentarse a todos los villanos que asolan la ciudad.",
    popularity: 1700.206,
    poster_path: "/suaooqn1Mnv60V19MoGxneMupJs.jpg",
    release_date: "2021-08-11",
    title: "Free Guy",
    video: false,
    vote_average: 7.8,
    vote_count: 392,
  },
  {
    adult: false,
    backdrop_path: "/xXHZeb1yhJvnSHPzZDqee0zfMb6.jpg",
    genre_ids: [28, 80, 53],
    id: 385128,
    original_language: "en",
    original_title: "F9",
    overview:
      "Dom Toretto lleva una vida tranquila con Letty y su hijo, el pequeño Brian, pero saben que el peligro siempre acecha. Esta vez, esa amenaza obligará a Dom a enfrentarse a los pecados de su pasado si quiere salvar a quienes más quiere. El equipo se vuelve a reunir para impedir un complot a escala mundial, liderado por uno de los asesinos más peligrosos y mejor conductor a los que se han enfrentado; un hombre que además es el hermano desaparecido de Dom, Jakob. Novena entrega de la famosa franquicia.",
    popularity: 1610.64,
    poster_path: "/TX1T3c3CDBN0y8iDNvlQbtiA5Z.jpg",
    release_date: "2021-05-19",
    title: "Fast & Furious 9",
    video: false,
    vote_average: 7.6,
    vote_count: 3098,
  },
  {
    adult: false,
    backdrop_path: "/wjQXZTlFM3PVEUmKf1sUajjygqT.jpg",
    genre_ids: [878, 28, 53],
    id: 581726,
    original_language: "en",
    original_title: "Infinite",
    overview:
      'Evan McCauley tiene habilidades que nunca aprendió y recuerdos de lugares que nunca ha visitado. Automedicado y al borde de un colapso mental, un grupo secreto que se hace llamar "Infinitos" acuden a su rescate, revelando que sus recuerdos son reales.',
    popularity: 1493.933,
    poster_path: "/niw2AKHz6XmwiRMLWaoyAOAti0G.jpg",
    release_date: "2021-06-10",
    title: "Infinito",
    video: false,
    vote_average: 7.4,
    vote_count: 826,
  },
  {
    adult: false,
    backdrop_path: "/yizL4cEKsVvl17Wc1mGEIrQtM2F.jpg",
    genre_ids: [28, 878, 12],
    id: 588228,
    original_language: "en",
    original_title: "The Tomorrow War",
    overview:
      "Un día el mundo se paraliza cuando un grupo de viajeros en el tiempo se transporta desde el año 2051 para entregar un mensaje urgente: La humanidad está perdiendo la guerra mundial contra una especie alienígena letal. La única esperanza de supervivencia es que los soldados y los ciudadanos del presente sean transportados al futuro y se unan a la lucha. Entre los reclutados está el profesor de instituto y padre de familia Dan Forester (Chris Pratt) quien, decidido a salvar el mundo por su hija, se une a una brillante científica (Yvonne Strahovski) y a su padre (J.K. Simmons) en una búsqueda desesperada por reescribir el destino del planeta.",
    popularity: 1461.785,
    poster_path: "/tzp6VzED2TBc02bkYoYnQa6r2OK.jpg",
    release_date: "2021-06-30",
    title: "La guerra del mañana",
    video: false,
    vote_average: 8.2,
    vote_count: 3618,
  },
  {
    adult: false,
    backdrop_path: "/gX5UrH1TLVVBwI7WxplW43BD6Z1.jpg",
    genre_ids: [16, 35, 12, 10751],
    id: 459151,
    original_language: "en",
    original_title: "The Boss Baby: Family Business",
    overview:
      "Los hermanos Templeton se han convertido en adultos y se han alejado el uno del otro, pero un nuevo jefe bebé con un enfoque de vanguardia está a punto de unirlos nuevamente e inspirar un nuevo negocio familiar.",
    popularity: 1355.6,
    poster_path: "/3XYeAnIdjTiHZehtKcNzsyBwtcz.jpg",
    release_date: "2021-07-01",
    title: "El bebé jefazo 2: Negocios de familia",
    video: false,
    vote_average: 7.8,
    vote_count: 1240,
  },
  {
    adult: false,
    backdrop_path: "/rUoGZuscSG4fQP3I56ndadu2A8E.jpg",
    genre_ids: [28, 35],
    id: 729720,
    original_language: "fr",
    original_title: "Le Dernier Mercenaire",
    overview:
      "Un misterioso ex agente del servicio secreto debe regresar urgentemente a Francia cuando su hijo separado es acusado falsamente por el gobierno de tráfico de armas y drogas, luego de un error cometido por un burócrata demasiado entusiasta y una operación de la mafia.",
    popularity: 1319.109,
    poster_path: "/mXmY5F0212bMg5ZbAlVTB3cWBQi.jpg",
    release_date: "2021-07-30",
    title: "El último mercenario",
    video: false,
    vote_average: 6.9,
    vote_count: 291,
  },
  {
    adult: false,
    backdrop_path: "/620hnMVLu6RSZW6a5rwO8gqpt0t.jpg",
    genre_ids: [16, 35, 10751, 14],
    id: 508943,
    original_language: "en",
    original_title: "Luca",
    overview:
      "Ambientada en un precioso pueblo costero de la Riviera italiana, narra la historia sobre el paso a la edad adulta de un chico que vive un verano inolvidable lleno de helados, pasta e infinitos paseos en scooter. Luca comparte estas aventuras con su nuevo mejor amigo, pero toda la diversión se ve amenazada por un secreto muy profundo: él es un monstruo marino de un mundo que yace bajo la superficie del agua.",
    popularity: 1308.514,
    poster_path: "/j93NHWoTjdsL4sdz058M3AvKrMy.jpg",
    release_date: "2021-06-17",
    title: "Luca",
    video: false,
    vote_average: 8.1,
    vote_count: 4104,
  },
  {
    adult: false,
    backdrop_path: "/6tPOZmNQ1tbzlhcMmyhYN1a1dEh.jpg",
    genre_ids: [28, 53],
    id: 809968,
    original_language: "pl",
    original_title: "Bartkowiak",
    overview:
      "Tras el fallecimiento de su hermano en un accidente de coche, un joven luchador se hace cargo del club familiar y pronto se da cuenta de que esa muerte no fue accidental.",
    popularity: 1026.446,
    poster_path: "/kOVko9u2CSwpU8zGj14Pzei6Eco.jpg",
    release_date: "2021-07-28",
    title: "Bartkowiak",
    video: false,
    vote_average: 5.9,
    vote_count: 85,
  },
  {
    adult: false,
    backdrop_path: "/8yhWlFcJ8zCqjfCvLy3lWFuawR1.jpg",
    genre_ids: [878, 9648, 10749],
    id: 579047,
    original_language: "en",
    original_title: "Reminiscence",
    overview:
      "En un futuro cercano, Nicolas Bannister (Hugh Jackman) tiene un negocio que consiste en que sus clientes puedan revivir cualquier recuerdo que deseen. Su vida cambia cuando conoce a Mae (Rebecca Ferguson), una mujer que sólo acude a la consulta para poder recordar dónde dejó sus llaves. Pero este encuentro, pronto se convierte en un apasionado romance. Sin embargo, un día Mae desaparece sin razón y Nick se queda desolado. Hará todo lo posible por encontrarla, lo que implicará volver al pasado para descubrir la verdad sobre la mujer de la que se ha enamorado.",
    popularity: 1011.51,
    poster_path: "/rDNw3PUbdslsctcJ6Db32g4A4FA.jpg",
    release_date: "2021-08-19",
    title: "Reminiscencia",
    video: false,
    vote_average: 7.5,
    vote_count: 291,
  },
  {
    adult: false,
    backdrop_path: "/wPjtacig0kIkVcTQmXoNt6jbMwo.jpg",
    genre_ids: [28, 35],
    id: 617502,
    original_language: "en",
    original_title: "Jolt",
    overview:
      "Una chica dura con tendencias ligeramente homicidas y que no controla la ira se da descargas con un chaleco de electrodos para volver a la normalidad si le entran las ganas de matar. Cuando asesinan al primer hombre del que se ha enamorado, empieza un desenfreno vengativo para encontrar al asesino, al mismo tiempo que la policía va tras ella porque la considera sospechosa.",
    popularity: 1009.379,
    poster_path: "/gYZAHan5CHPFXORpQMvOjCTug4E.jpg",
    release_date: "2021-07-15",
    title: "Jolt",
    video: false,
    vote_average: 6.8,
    vote_count: 556,
  },
  {
    adult: false,
    backdrop_path: "/tehpKMsls621GT9WUQie2Ft6LmP.jpg",
    genre_ids: [27, 28, 53],
    id: 602223,
    original_language: "en",
    original_title: "The Forever Purge",
    overview:
      "Para los miembros de un movimiento clandestino, ya no es suficiente una noche anual de anarquía y asesinatos, así que deciden devolver a Estados Unidos el caos y las masacres sin fin, donde nadie volverá a estar a salvo... jamás. Adela y su esposo Juan viven en Texas, donde él trabaja como peón en un rancho para la adinerada familia Tucker. En la mañana después de la tradicional purga, una banda de asesinos enmascarados ataca violenta e ilegalmente a la familia Tucker. Tras este hecho, la familia texana se ve obligada a unirse con Juan y su esposa para enfrentar un país entero a punto de colapsar, que se hunde en un mar de caos y de sangre. Quinta y última entrega de la saga 'The Purge'.",
    popularity: 1000.124,
    poster_path: "/5yvawJviOjb2nUFvHGXcCpGVTqy.jpg",
    release_date: "2021-06-30",
    title: "La Purga: Infinita",
    video: false,
    vote_average: 7.5,
    vote_count: 1058,
  },
  {
    adult: false,
    backdrop_path: "/pUc51UUQb1lMLVVkDCaZVsCo37U.jpg",
    genre_ids: [53, 27],
    id: 482373,
    original_language: "en",
    original_title: "Don't Breathe 2",
    overview:
      "El ciego se ha estado escondiendo durante años en una cabaña aislada y ha acogido y criado a una niña que perdió a sus padres en un incendio en una casa. Su tranquila existencia se hace añicos cuando un grupo de secuestradores aparece y se lleva a la niña, lo que obliga al Ciego a dejar su refugio seguro para rescatarla.",
    popularity: 982.894,
    poster_path: "/nR8kDV11jeRWdcjMwavbqFrJolR.jpg",
    release_date: "2021-08-12",
    title: "No Respires 2",
    video: false,
    vote_average: 7.3,
    vote_count: 67,
  },
];
